/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.intuit.dsl.ServiceRuntimeModule;
import com.intuit.dsl.ServiceStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ServiceIdeSetup extends ServiceStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ServiceRuntimeModule(), new ServiceIdeModule()));
	}
	
}
