/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ServiceRuntimeModule extends AbstractServiceRuntimeModule {
}
