/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ServiceStandaloneSetup extends ServiceStandaloneSetupGenerated {

	public static void doSetup() {
		new ServiceStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
