/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ServiceValidator extends AbstractServiceValidator {
	
	
}
