/*
 * generated by Xtext 2.25.0
 */
package com.intuit.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ServiceUiModule extends AbstractServiceUiModule {

	public ServiceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
